---
- name: restart a fltsrv01-03  ec2 machines
  amazon.aws.ec2_instance:
    state: restarted
    instance_ids: "{{ items }}"
  vars:
    items: "{{ ec2_flt_hosts }}"

- name: Sleep for 60 seconds wait
  ansible.builtin.wait_for:
    timeout: 60
