---
- name: restart a fds ec2 machines
  amazon.aws.ec2_instance:
    state: restarted
    instance_ids: "{{ items }}"
  vars:
    items: "{{ ec2_fdss_host }}"

- name: Sleep for 60 seconds wait
  ansible.builtin.wait_for:
    timeout: 60
