---
- name: restart a wks01-03 ec2 machine
  amazon.aws.ec2_instance:
    state: restarted
    instance_ids: "{{ items }}"
  vars:
    items: "{{ ec2_wks_hosts }}"

- name: Sleep for 60 seconds wait
  ansible.builtin.wait_for:
    timeout: 60
