---
- name: restart a particular instance by its ID
  amazon.aws.ec2_instance:
    state: restarted
    instance_ids: "{{ items }}"
  vars:
    items: "{{ ec2_free_hosts }}"

- name: Sleep for 60 seconds wait
  ansible.builtin.wait_for:
    timeout: 60
